apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-js-frontend
  template:
    metadata:
      labels:
        app: next-js-frontend
    spec:
      containers:
      - name: next-js-frontend
        image: next-js-frontend:latest
        env:
        - name: "PORT"
          value: "3001"
        - name: "BACKEND_URL"
          value: "http://backend-service:8080"
