apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      labels:
        app: seed
    spec:
      containers:
      - name: seed
        image: seed-pg
      restartPolicy: OnFailure